export const mockCollectionData = [
  {
    id: '1',
    name: 'Cyberpunk',
    image: require('../assets/images/collections/cyberPunk1.png'),
    price: '0.23',
    creator: 'Anna',
    creatorImage: require('../assets/images/creators/creator1.jpg'),
  },
  {
    id: '2',
    name: 'Cyberpunk',
    image: require('../assets/images/collections/cyberPunk2.jpeg'),
    price: '1.23',
    creator: 'Lima',
    creatorImage: require('../assets/images/creators/creator2.jpg'),
  },
  {
    id: '3',
    name: 'Cyberpunk',
    image: require('../assets/images/collections/cyberPunk3.jpeg'),
    price: '0.10',
    creator: 'Jonh Doe',
    creatorImage: require('../assets/images/creators/creator3.jpg'),
  },
  {
    id: '4',
    name: 'Cyberpunk',
    image: require('../assets/images/collections/cyberPunk4.jpeg'),
    price: '0.50',
    creator: 'David Smith',
    creatorImage: require('../assets/images/creators/creator4.jpg'),
  },
  {
    id: '5',
    name: 'Cyberpunk',
    image: require('../assets/images/collections/cyberPunk5.jpeg'),
    price: '0.50',
    creator: 'Millen Mart',
    creatorImage: require('../assets/images/creators/creator5.jpg'),
  },
];